export const FETCHING_CASELIST = 'FETCHING_CASELIST'
export const FETCHING_CASELIST_SUCCESS = 'FETCHING_CASELIST_SUCCESS'
export const FETCHING_CASELIST_ERROR = 'FETCHING_CASELIST_ERROR'
export const FETCHING_CASELIST_REFRESH = 'FETCHING_CASELIST_REFRESH'

export const FETCHING_MYCASELIST = 'FETCHING_MYCASELIST'
export const FETCHING_MYCASELIST_SUCCESS = 'FETCHING_MYCASELIST_SUCCESS'
export const FETCHING_MYCASELIST_ERROR = 'FETCHING_MYCASELIST_ERROR'
export const FETCHING_MYCASELIST_REFRESH = 'FETCHING_MYCASELIST_REFRESH'
export const FETCHING_MYCASELIST_NODATA = 'FETCHING_MYCASELIST_NODATA'

export const FETCHING_FOLLOWINGCASELIST = 'FETCHING_FOLLOWINGCASELIST'
export const FETCHING_FOLLWINGCASELIST_SUCCESS = 'FETCHING_FOLLWINGCASELIST_SUCCESS'
export const FETCHING_FOLLWINGCASELIST_ERROR = 'FETCHING_FOLLWINGCASELIST_ERROR'
export const FETCHING_FOLLWINGCASELIST_REFRESH = 'FETCHING_FOLLWINGCASELIST_REFRESH'

export const FETCHING_SORT_CASELIST = 'FETCHING_SORT_CASELIST'
export const FETCHING_SORT_CASELIST_SUCCESS = 'FETCHING_SORT_CASELIST_SUCCESS'
export const FETCHING_SORT_CASELIST_ERROR = 'FETCHING_SORT_CASELIST_ERROR'
export const FETCHING_SORT_CASELIST_REFRESH = 'FETCHING_SORT_CASELIST_REFRESH'

export const FETCHING_FILTER_CASELIST = 'FETCHING_FILTER_CASELIST'
export const FETCHING_FILTER_CASELIST_SUCCESS = 'FETCHING_FILTER_CASELIST_SUCCESS'
export const FETCHING_FILTER_CASELIST_ERROR = 'FETCHING_FILTER_CASELIST_ERROR'
export const FETCHING_FILTER_CASELIST_REFRESH = 'FETCHING_FILTER_CASELIST_REFRESH'

export const SET_FOLLOW_TEXT = 'SET_FOLLOW_TEXT'

export const SET_MYCASELIST_TEXT = 'SET_MYCASELIST_TEXT'

export const SET_NOTIFICATION_PAGE = 'SET_NOTIFICATION_PAGE'

export const SET_FILTER_TEXT = 'SET_FILTER_TEXT'

export const FETCHING_PRAYER_CLICK = 'FETCHING_PRAYER_CLICK'

export const MANAGE_EDIT_TEXT = 'MANAGE_EDIT_TEXT'

export const SHARE_APP = 'SHARE_APP'

export const SAVE_SETTING_DATA = 'SAVE_SETTING_DATA'

export const LOGOUT_APP = 'LOGOUT_APP'

export const SET_POINTS = 'SET_POINTS'
