# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'healingg' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks

  # Pods for healingg
  pod 'Firebase/Core', '~> 5.15.0'
  pod 'GoogleSignIn', '~> 4.4.0'
  pod 'Firebase/Messaging', '~> 5.15.0'
  pod 'RNFirebase', :path => '../node_modules/react-native-firebase/ios'

    # Explicitly include Yoga if you are using RN >= 0.42.0
    pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
    pod 'React', :path => '../node_modules/react-native'
    # Third party deps podspec link
    pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
    #pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
    pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'
    
    #pod 'react-native-fbsdk', :path => '../node_modules/react-native-fbsdk'
    pod 'FBSDKCoreKit', '~> 5.6.0'
    pod 'FBSDKLoginKit', '~> 5.6.0'
    pod 'FBSDKShareKit', '~> 5.6.0'
    pod 'GoogleIDFASupport', '~> 3.14.0'
  pod 'react-native-splash-screen', :path => '../node_modules/react-native-splash-screen'

end
post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.name == "React"
      target.remove_from_project
    end
    if target.name == "yoga"
        target.remove_from_project
    end
  end
end
